### ISSUE TITLE
CmsBlockTestCase instanceof PhpBlock test

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-testsuite#10]
### What steps will reproduce the problem?
The CmsBlockTestCase does currently not check whether it is an instance of PhpBlock or not.

### What is the expected result?
It should check whether the block is an instance of PhpBlock or not.

### Additional infos
- https://github.com/luyadev/luya-testsuite/blob/master/tests/data/TestBlock.php
- https://github.com/luyadev/luya-testsuite/blob/master/src/cases/CmsBlockTestCase.php

_I'll make a PR_

**Comment by JohnnyMcWeed** [comment]
I did something as you can see here:
- https://github.com/luyadev/luya-testsuite/compare/master...JohnnyMcWeed:issue10

but couldn't run the test due to 
```
Fatal error: Uncaught yii\web\HeadersAlreadySentException: Headers already sent 
in ... vendor\phpunit\phpunit\src\Util\Printer.php on line 114. 
in ... vendor\yiisoft\yii2\web\Response.php on line 366
```

**Comment by nadar** [comment]
The blocks should be instance of BlockInterface (https://luya.io/api/luya-cms-base-BlockInterface) not PhpBlock

**Comment by nadar** [comment]
Does the problem still persists or can we close this? Let me know if i should reopen.
