### ISSUE TITLE
Db component not defined while luyadev

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-testsuite#33]
While execute _luyadev_ the core commands are disabled. But the bootstrap of the test suite still adding `generatefixture` to controllermap. Otherwise I will get an exception that the `db` component is not defined.
Or did I configure something wrong?

In [line 24](https://github.com/luyadev/luya-testsuite/blob/master/src/Bootstrap.php#L24) of the Bootstrap should check the enableCoreCommands:

`if ($app instanceof Application && $app->enableCoreCommands) {`

**Comment by nadar** [comment]
Or we could also make the database connection check lazy with a getter instead of init method (https://github.com/luyadev/luya-testsuite/blob/master/src/commands/GenerateFixtureController.php#L57).

but yes enableCoreCommands might be the better solution :+1:
